[package]
name = "one"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.0.5"
solana-sdk = "2.0.5"
rand = "0.8" 
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }  # For async support
